@startuml diagrama

class Usuario
class Foco{
    -EstadoFoco estado
    +encender()
    +apagar()
    +EstadoFoco Mostrarestado()
}
class EstadoFoco

Usuario o-- Foco
Foco *-- EstadoFoco
EstadoFoco --|> bool

@enduml